# Lesson 1 Practice: NumPy Part 1
Use this notebook to follow along with the lesson in the corresponding lesson notebook: [L01-Numpy_Part1-Lesson.ipynb](./L01-Numpy_Part1-Lesson.ipynb).  



## Instructions
Follow along with the teaching material in the lesson. Throughout the tutorial sections labeled as "Tasks" are interspersed and indicated with the icon: ![Task](http://icons.iconarchive.com/icons/sbstnblnd/plateau/16/Apps-gnome-info-icon.png). You should follow the instructions provided in these sections by performing them in the practice notebook.  When the tutorial is completed you can turn in the final practice notebook. For each task, use the cell below it to write and test your code.  You may add additional cells for any task as needed or desired.  

## Task 1a: Setup

In the practice notebook, import the following packages:
+ `numpy` as `np`

In [2]:
import numpy as np

## Task 2a: Creating Arrays

In the practice notebook, perform the following.  
- Create a 1-dimensional numpy array and print it.
- Create a 2-dimensional numpy array and print it.
- Create a 3-dimensional numpy array and print it.

In [5]:
an_array = np.array([1,2,3,4])


In [7]:
print(an_array)

[1 2 3 4]


In [9]:
a_2D_array = np.array([[1,3], [6,8]])

In [10]:
print(a_2D_array)

[[1 3]
 [6 8]]


In [11]:
a_3D_array = np.array([[[5,7,9], [2,6,9], [2,6,2]]])

In [12]:
print(a_3D_array)

[[[5 7 9]
  [2 6 9]
  [2 6 2]]]


## Task 3a: Accessing Array Attributes

In the practice notebook, perform the following.

- Create a NumPy array.
- Write code that prints these attributes (one per line): `ndim`, `shape`, `size`, `dtype`, `itemsize`, `data`, `nbytes`.
- Add a comment line, before each line describing what value the attribute returns. 


In [13]:
#Returns the number of array dimensions.
print(an_array.ndim)

1


In [15]:
#Returns a tupple of the array's dimensions.
print(a_2D_array.shape)

(2, 2)


In [16]:
#Returns the number of elements in the array.
print(a_3D_array.size)

9


In [17]:
#Returns the data type of the array
print(a_3D_array.dtype)

int32


In [18]:
#Returns the length of one array elements in bytes
print(a_3D_array.itemsize)

4


In [20]:
#Returns the Python buffer object pointing to start of array's data
print(a_3D_array.data)

In [22]:
#Returns the total number of bytes consumed by the elements in the array.
print(a_3D_array.nbytes)

36


## Task 4a: Initializing Arrays

In the practice notebook, perform the following.

+ Create an initialized array by using these functions:  `ones`, `zeros`, `empty`, `full`, `arange`, `linspace` and `random.random`. Be sure to follow each array creation with a call to `print()` to display your newly created arrays. 
+ Add a comment above each function call describing what is being done.  

In [23]:
#Creates a new array with 4 rows and columns filled with 1's
unos = np.ones((4, 4))
print(unos)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [24]:
#Creates a new array with 4 rows and columns filled with 0's
ceros = np.zeros((4, 4))
print(ceros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [25]:
#Creats a new empty array with 3 rows and 3 columns
vacio = np.empty((3, 3))
print(vacio)

[[0.000e+000 0.000e+000 0.000e+000]
 [0.000e+000 0.000e+000 6.107e-321]
 [0.000e+000 0.000e+000 0.000e+000]]


In [27]:
#Returns a new array of a given shape and type with a fill value.
lleno = np.full((2, 3), 7)
print(lleno)

[[7 7 7]
 [7 7 7]]


In [28]:
#Returns a new array with evenly spaced values between a given interval.
arreglo = np.arange(1, 8)
print(arreglo)

[1 2 3 4 5 6 7]


In [33]:
#Returns a new array of evenly spaced numbers over an interval
linea = np.linspace(4, 10, num=3)
print(linea)

[ 4.  7. 10.]


In [34]:
#Returns random single value of an array of random values between 0 and 1
aleatorio = np.random.random((3, 3))
print(aleatorio)

[[0.85408302 0.26248225 0.01426613]
 [0.24523987 0.29618933 0.93327121]
 [0.78095276 0.41368873 0.71238232]]


## Task 5a:  Broadcasting Arrays

In the practice notebook, perform the following.

+ Create two arrays of differing sizes but compatible with broadcasting.
+ Perform addition, multiplication and subtraction.
+ Create two additional arrays of differing size that do not meet the rules for broadcasting and try a mathematical operation.  

In [24]:
#Creates the arrays to be used
A = np.array((3,2))
B = np.array([[[1, 6], [2, 7], [8, 3]]])

In [31]:
#Prints the arrays
print(f"A shape: {A.shape}")
print(f"B shape: {B.shape}")

A shape: (2,)
B shape: (1, 3, 2)


In [26]:
#Adds the arrays
A + B

array([[[ 4,  8],
        [ 5,  9],
        [11,  5]]])

In [27]:
#Multiplies the arrays
A * B

array([[[ 3, 12],
        [ 6, 14],
        [24,  6]]])

In [28]:
#Subtracts the arrays
A - B

array([[[ 2, -4],
        [ 1, -5],
        [-5, -1]]])

In [33]:
#Creating arrays that have different dimensions but do not meet criteria for broadcasting
Fail_A = np.ones((4, 5))
Fail_B = np.random.random((3, 2, 3))

In [34]:
#prints the new arrays
print(Fail_A)
print(Fail_B)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[[0.50902439 0.64044296 0.16068594]
  [0.40847623 0.93352212 0.69322117]]

 [[0.14048248 0.72496315 0.21184811]
  [0.29371431 0.27317319 0.93358233]]

 [[0.61305225 0.12649394 0.96482343]
  [0.68339884 0.5888324  0.25711797]]]


In [35]:
#Printing the shape of the new arrays
print(f"Fail_A shape: {Fail_A.shape}")
print(f"Fail_B shape: {Fail_B.shape}")

Fail_A shape: (4, 5)
Fail_B shape: (3, 2, 3)


In [36]:
#Checking to see if we can perform math on them
Fail_A + Fail_B

ValueError: operands could not be broadcast together with shapes (4,5) (3,2,3) 

## Task 6a: Math/Stats Aggregate Functions

In the practice notebook, perform the following.

+ Create three to five arrays
+ Experiment with each of the aggregation functions: `sum`, `minimum`, `maximum`, `cumsum`, `mean`, `np.corrcoef`, `np.std`, `np.var`. 
+ For each function call, add a comment line above it that describes what it does.  
```


In [49]:
#Creating some more arrays to play with
Alpha = np.random.random((4, 4))
Beta = np.ones((4, 4))
Gamma = np.random.random((4, 4))

In [50]:
#printing these arrays
print(Alpha)
print(Beta)
print(Gamma)

[[6.76087668e-01 7.56157306e-01 4.45036475e-01 1.12845589e-01]
 [6.78078959e-01 2.96499496e-01 6.88559876e-03 7.23763465e-01]
 [6.89940574e-01 2.55985139e-01 3.11720385e-01 1.26194051e-01]
 [5.56724141e-04 6.31187171e-01 4.61030204e-01 2.00336239e-01]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0.59621824 0.04219114 0.04440367 0.52865647]
 [0.10056887 0.26256716 0.29048927 0.66195333]
 [0.83136448 0.38585051 0.75578942 0.59894853]
 [0.37096728 0.92432117 0.33624407 0.97354034]]


In [51]:
#Adding Beta and Gamma arrays
Beta + Gamma

array([[1.59621824, 1.04219114, 1.04440367, 1.52865647],
       [1.10056887, 1.26256716, 1.29048927, 1.66195333],
       [1.83136448, 1.38585051, 1.75578942, 1.59894853],
       [1.37096728, 1.92432117, 1.33624407, 1.97354034]])

In [52]:
#Summing the elements of Alpha
np.sum(Alpha)

6.372305044988506

In [53]:
#Finding the minimum element of the arrays
np.minimum(Alpha, Beta, Gamma)

array([[6.76087668e-01, 7.56157306e-01, 4.45036475e-01, 1.12845589e-01],
       [6.78078959e-01, 2.96499496e-01, 6.88559876e-03, 7.23763465e-01],
       [6.89940574e-01, 2.55985139e-01, 3.11720385e-01, 1.26194051e-01],
       [5.56724141e-04, 6.31187171e-01, 4.61030204e-01, 2.00336239e-01]])

In [55]:
#Finding the maximum of the arrays
np.maximum(Alpha, Beta, Gamma)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [61]:
#Finding the cummulative sum of Alpha
np.cumsum(Alpha,axis=1)

array([[6.76087668e-01, 1.43224497e+00, 1.87728145e+00, 1.99012704e+00],
       [6.78078959e-01, 9.74578456e-01, 9.81464055e-01, 1.70522752e+00],
       [6.89940574e-01, 9.45925713e-01, 1.25764610e+00, 1.38384015e+00],
       [5.56724141e-04, 6.31743895e-01, 1.09277410e+00, 1.29311034e+00]])

In [63]:
#Finding the average of Gamma
np.mean(Gamma)

1.0

In [ ]:
#Finding the pearson coefficient of Alpha

In [64]:
np.corrcoef(Alpha)

array([[ 1.        , -0.27631359,  0.59424875,  0.25741338],
       [-0.27631359,  1.        ,  0.19201132, -0.76064406],
       [ 0.59424875,  0.19201132,  1.        , -0.57498757],
       [ 0.25741338, -0.76064406, -0.57498757,  1.        ]])

In [65]:
#Finding the standard deviation of Gamma
np.std(Gamma)

0.0

In [66]:
#Returning the variance of Alpha
np.var(Alpha)

0.0674421219485514

## Task 6b: Logical Aggregate Functions

In the practice notebook, perform the following.

+ Create two arrays containing boolean values.
+ Experiment with each of the aggregation functions: `logical_and`, `logical_or`, `logical_not`. 
+ For each function call, add a comment line above it that describes what it does.  
```

In [80]:
#creating two more arrays with Boolean values
AA = [True, False, False, True]
BB = [False, True, False, True]

In [81]:
#performing a logical "and"
np.logical_and(AA, BB)

array([False, False, False,  True])

In [82]:
#perform a logical "or"
np.logical_or(AA, BB)

array([ True,  True, False,  True])

In [84]:
#perform a logical "not"
np.logical_not(AA)

array([False,  True,  True, False])