# Lesson 2 Practice: NumPy Part 2
Use this notebook to follow along with the lesson in the corresponding lesson notebook: [L02-Numpy_Part2-Lesson.ipynb](./L02-Numpy_Part2-Lesson.ipynb).  


## Instructions
Follow along with the teaching material in the lesson. Throughout the tutorial sections labeled as "Tasks" are interspersed and indicated with the icon: ![Task](http://icons.iconarchive.com/icons/sbstnblnd/plateau/16/Apps-gnome-info-icon.png). You should follow the instructions provided in these sections by performing them in the practice notebook.  When the tutorial is completed you can turn in the final practice notebook. For each task, use the cell below it to write and test your code.  You may add additional cells for any task as needed or desired. 

## Task 1a: Setup

In the practice notebook, import the following packages:
+ `numpy` as `np`

In [49]:
#importing numpy as np
import numpy as np

## Task 2a: Indexing by Subsetting and Slicing

In the practice notebook perform the following:

1. Create (or re-use) 3 arrays, each containing three dimensions.
2. Slice each of these arrays so that:
    + One element / number is returned.
    + One dimension is returned.
    + A subset of a dimension is returned.
3. What is the difference between `[x:]` and `[x, ...]`? (hint, try each on high-dimension arrays).
    
*Exactly what you choose to return is not imporant at this point, the goal of this task is to train you so that if you are given an n-dimension NumPy array, you can write an index or slice that returns a subset of desired positions.*

In [35]:
#Create the three arrays
AA = np.random.random((3,3))
BB = np.ones((3,3))
CC = np.random.random((3,3))
#printing the three arrays
print(AA)
print(BB)
print(CC)

[[0.79375642 0.92955619 0.93720582]
 [0.18546459 0.21397427 0.77696516]
 [0.79720115 0.38293529 0.89603148]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.54353522 0.33268299 0.78570849]
 [0.92740874 0.58078908 0.25002726]
 [0.05199928 0.96809728 0.79953735]]


In [36]:
#Get the the 3rd column 3rd row elements
AA[2,2]

0.8960314775132502

In [37]:
#Get the elements from the 2nd row of BB
BB[2:]

array([[1., 1., 1.]])

In [38]:
#Get items from the first index to last 
CC[0:-1]

array([[0.54353522, 0.33268299, 0.78570849],
       [0.92740874, 0.58078908, 0.25002726]])

In [39]:
#Gets all items in the array from the beginning
AA[0:]

array([[0.79375642, 0.92955619, 0.93720582],
       [0.18546459, 0.21397427, 0.77696516],
       [0.79720115, 0.38293529, 0.89603148]])

In [40]:
#Gets first row elements
CC[0,]

array([0.54353522, 0.33268299, 0.78570849])

## Task 3a: Boolean Indexing

In the practice notebook perform the following:

+ Experiment with the following boolean conditionals to generate boolean arrays for indexing:
  + Greater than
  + Less than
  + Equals
  + Combine two or more of the above with:
      + or `|`
      + and `&`

You can create arrays or use existing ones

In [41]:
#Return a list of Boolvean values for the conditional statement greater than 0.5
CC > 0.5 

array([[ True, False,  True],
       [ True,  True, False],
       [False,  True,  True]])

In [42]:
#Returns the elements from CC greater than 0.5
CC[CC>0.5]

array([0.54353522, 0.78570849, 0.92740874, 0.58078908, 0.96809728,
       0.79953735])

In [43]:
#Returns an array of Boolean values for the conditional statement less than 0.5
AA < 0.5

array([[False, False, False],
       [ True,  True, False],
       [False,  True, False]])

In [44]:
#Returns the elements from AA less than 0;5

AA[AA < 0.5]



array([0.18546459, 0.21397427, 0.38293529])

In [43]:
#Returns the boolean values for elements equal to the statement
AA == 0.47644179

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [42]:
#Returns the elements that meet the conditional statment if any
AA[AA == 0.47644179]

array([], dtype=float64)

In [46]:
#Returns boolean values for elements less than 0.5 in CC and greater than 0.5 in AA
(CC < 0.5) & (AA > 0.5)


array([[False,  True, False],
       [False, False,  True],
       [ True, False, False]])

In [47]:
#Returns boolean values for elements less than 0.5 in AA or greater than 0.5 in CC
(AA < 0.5) | (CC > 0.5)

array([[ True, False,  True],
       [ True,  True, False],
       [False,  True,  True]])

## Task 4a: Getting Help

In the practice notebook perform the following:

+ In the code cell below, call `help()` on two of the following functions: `np.transpose()`, `np.reshape()`, `np.resize()`, `np.ravel()`, `np.append()`, `np.delete()`, `np.concatenate()`, `np.vstack()`, `np.hstack()`, `np.column_stack()`, `np.vsplit()`, `np.hsplit()` 
+ Respond to this question: Did you understand the help docuemntation? Could you use the function just by looking at what the help says about it?  

In [66]:
#Provides help the ravel function
help(np.ravel)

Help on function ravel in module numpy:

ravel(a, order='C')
    Return a contiguous flattened array.
    
    A 1-D array, containing the elements of the input, is returned.  A copy is
    made only if needed.
    
    As of NumPy 1.10, the returned array will have the same type as the input
    array. (for example, a masked array will be returned for a masked array
    input)
    
    Parameters
    ----------
    a : array_like
        Input array.  The elements in `a` are read in the order specified by
        `order`, and packed as a 1-D array.
    order : {'C','F', 'A', 'K'}, optional
    
        The elements of `a` are read using this index order. 'C' means
        to index the elements in row-major, C-style order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest.  'F' means to index the elements
        in column-major, Fortran-style order, with the
        first index changing fastest, and the last index changing
       

In [71]:
#returns the CC array
print(CC)
#Flattens CC by using the ravel function and sets it equal to new array ccc
CCC = np.ravel(CC)
#prints array ccc
print(CCC)

[[0.23470394 0.70689325 0.24951123]
 [0.93052183 0.89275487 0.23339367]
 [0.44150886 0.38863471 0.98322487]]
[0.23470394 0.70689325 0.24951123 0.93052183 0.89275487 0.23339367
 0.44150886 0.38863471 0.98322487]


In [67]:
#Provides information on hstack function
help(np.hstack)

Help on function hstack in module numpy:

hstack(tup)
    Stack arrays in sequence horizontally (column wise).
    
    This is equivalent to concatenation along the second axis, except for 1-D
    arrays where it concatenates along the first axis. Rebuilds arrays divided
    by `hsplit`.
    
    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.
    
    Parameters
    ----------
    tup : sequence of ndarrays
        The arrays must have the same shape along all but the second axis,
        except 1-D arrays which can be any length.
    
    Returns
    -------
    stacked : ndarray
        The array formed by stacking the given arrays.
    
    See Also
    --------
    stack : Join a sequence of arrays along a new axis.
    vstack : Stac

In [ ]:
#I think the documentation helps to understand what functions will accept 
#but I think it is best to get a 'hands on' experience with them by trying to use them and reading the documentation

## Task 5a: Transposing an Array

In the practice notebook perform the following:

+ Create a matrix of any size and transpose it.

In [72]:
#creates a new aray
DD = np.random.random((4,4))
#prints the DD array
print(DD)

[[0.08821004 0.58619343 0.4820084  0.77815281]
 [0.63393163 0.2396803  0.01445805 0.46545536]
 [0.81126612 0.08036338 0.26522937 0.71451167]
 [0.22550693 0.08146966 0.29760337 0.54514735]]


In [74]:
#prints the transpose of the DD array
print(np.transpose(DD))

[[0.08821004 0.63393163 0.81126612 0.22550693]
 [0.58619343 0.2396803  0.08036338 0.08146966]
 [0.4820084  0.01445805 0.26522937 0.29760337]
 [0.77815281 0.46545536 0.71451167 0.54514735]]


In [75]:
#prints the alternative way of getting the tranpose of DD
print(DD.T)

[[0.08821004 0.63393163 0.81126612 0.22550693]
 [0.58619343 0.2396803  0.08036338 0.08146966]
 [0.4820084  0.01445805 0.26522937 0.29760337]
 [0.77815281 0.46545536 0.71451167 0.54514735]]


## Task 5b: Reshaping an Array

In the practice notebook peform the following:

+ Create a matrix and resize it by adding 2 extra columns
+ Create a matrix and resize it by adding 1 extra row
+ Create a matrix of 8 x 2 and resize it to 4 x 4

In [79]:
#Creats the XX array
XX = np.array([1,2,3,4])
#prints the dimension of the XX array
print(XX.shape)

(4,)


In [86]:
#Resizes the XX array by adding two extra columns
np.resize(XX, (6,))

array([1, 2, 3, 4, 1, 2])

In [93]:
#Creats a YY array
YY = np.ones((4,5))
#prints the YY
print(YY)
#Prints the dimensions of YY
print(YY.shape)
#Resizes the YY array by adding another row
np.resize(YY, (5,5))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(4, 5)


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [96]:
#creats an array of 8 rows and 2 columns
TT = np.ones((8,2))
print(TT)
#resizes the array to an array of 4 rows and 4 columns
np.resize(TT, (4,4))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Task 5c: Appending to an Array

In the practice notebook perform the following:

 + Create a three dimensional array and append another row to the array
 + Append another colum to the array
 + Print the final results

In [52]:
#creats the 3D array
A_3D_Array = np.ones((3,3))
#prints the array
print(A_3D_Array)
#adding a row to the way by using the append function
Add_Row = np.append(A_3D_Array, np.ones((3,1)), axis=1)
print(Add_Row)
#adding a column by using the append function
Add_Col = np.append(Add_Row, np.ones((1,4)), axis=0)
print(Add_Col)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Task 5d: Inserting and Deleting Elements

In the practice notebook perform the following:

+ Examine the `help()` documentation for how to use the `insert()` and `delete()` functions.
+ Create a matrix and practice inserting a row and deleting a column.

In [20]:
#gets the documention for the insert function
help(np.insert)

Help on function insert in module numpy:

insert(arr, obj, values, axis=None)
    Insert values along the given axis before the given indices.
    
    Parameters
    ----------
    arr : array_like
        Input array.
    obj : int, slice or sequence of ints
        Object that defines the index or indices before which `values` is
        inserted.
    
        .. versionadded:: 1.8.0
    
        Support for multiple insertions when `obj` is a single scalar or a
        sequence with one element (similar to calling insert multiple
        times).
    values : array_like
        Values to insert into `arr`. If the type of `values` is different
        from that of `arr`, `values` is converted to the type of `arr`.
        `values` should be shaped so that ``arr[...,obj,...] = values``
        is legal.
    axis : int, optional
        Axis along which to insert `values`.  If `axis` is None then `arr`
        is flattened first.
    
    Returns
    -------
    out : ndarray
        A

In [53]:
#Creates a new array
some_array = np.random.random((3,3))
print(some_array)
#inserts the followoing elemetns as rows into some_array array
np.insert(some_array, [1], [[1], [2], [3]], axis=0)



[[0.37072957 0.28980747 0.50448028]
 [0.3729276  0.70925236 0.53330855]
 [0.25627495 0.60981032 0.57643084]]


array([[0.37072957, 0.28980747, 0.50448028],
       [1.        , 1.        , 1.        ],
       [2.        , 2.        , 2.        ],
       [3.        , 3.        , 3.        ],
       [0.3729276 , 0.70925236, 0.53330855],
       [0.25627495, 0.60981032, 0.57643084]])

In [28]:
#gets the document for the np.delete function
help(np.delete)

Help on function delete in module numpy:

delete(arr, obj, axis=None)
    Return a new array with sub-arrays along an axis deleted. For a one
    dimensional array, this returns those entries not returned by
    `arr[obj]`.
    
    Parameters
    ----------
    arr : array_like
      Input array.
    obj : slice, int or array of ints
      Indicate which sub-arrays to remove.
    axis : int, optional
      The axis along which to delete the subarray defined by `obj`.
      If `axis` is None, `obj` is applied to the flattened array.
    
    Returns
    -------
    out : ndarray
        A copy of `arr` with the elements specified by `obj` removed. Note
        that `delete` does not occur in-place. If `axis` is None, `out` is
        a flattened array.
    
    See Also
    --------
    insert : Insert elements into an array.
    append : Append elements at the end of an array.
    
    Notes
    -----
    Often it is preferable to use a boolean mask. For example:
    
    >>> mask = n

In [32]:
#Creates new array
someother_arr = np.random.random((3,3))
#prints the new array
print(someother_arr)
#deletes the third column elements
np.delete(someother_arr, 2, 1)

[[0.64704498 0.184403   0.16434473]
 [0.9827458  0.43075332 0.91964111]
 [0.66172727 0.71656962 0.10107768]]


array([[0.64704498, 0.184403  ],
       [0.9827458 , 0.43075332],
       [0.66172727, 0.71656962]])

## Task 5e: Joining Arrays

In the practice notebook perform the following:

+ Execute the code (in the cell below).
+ Examine the output from each of the function calls in the cell above. If needed to understand, review the help pages for each tool either using the `help()` command or the [Numpy Function Reference](https://docs.scipy.org/doc/numpy/reference/routines.html). 
+ Respond to the following question and respond in the second cell below.
  + Can you identify what is happening with each of them?

In [33]:
# Concatentate `my_array` and `x`: similar to np.append()
my_array = np.array([1,2,3,4])
x = np.array([1,1,1,1])
print("concatenate:")
print(np.concatenate((my_array, x)))

# Stack arrays row-wise
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
print("\nvstack:")
print(np.vstack((my_array, my_2d_array)))

# Stack arrays horizontally
print("\nhstack:")
print(np.hstack((my_2d_array, my_2d_array)))

# Stack arrays column-wise
print("\ncolumn_stack:")
print(np.column_stack((my_2d_array, my_2d_array)))

concatenate:
[1 2 3 4 1 1 1 1]

vstack:
[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]]

hstack:
[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]

column_stack:
[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]


## Task 5d: Splitting Arrays

In the practice notebook perform the following:

+ Execute the code (as shown below).
+ Examine the output from each of the function calls in the cell above. If needed to understand, review the help pages for each tool either using the `help()` command or the [Numpy Function Reference](https://docs.scipy.org/doc/numpy/reference/routines.html). 
+ Respond to the following question and respond in the second cell below.
  + Can you identify what is happening with each of them?

In [54]:
# Create a 2D array.
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
print("original:")
print(my_2d_array)

# Split `my_stacked_array` horizontally at the 2nd index
print("\nhsplit:")
print(np.hsplit(my_2d_array, 2))

# Split `my_stacked_array` vertically at the 2nd index
print("\nvsplit:")
print(np.vsplit(my_2d_array, 2))

original:
[[1 2 3 4]
 [5 6 7 8]]

hsplit:
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]

vsplit:
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]
